# Generated by Django 5.1.6 on 2025-02-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0002_remove_movie_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=300)),
                ("path", models.ImageField(upload_to="files/archives")),
            ],
        ),
    ]
