# Generated by Django 5.1.6 on 2025-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.FileField(upload_to="files/archives"),
        ),
    ]
