# Generated by Django 5.1.6 on 2025-02-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="file",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="actuator",
            field=models.FileField(default=None, upload_to="files/"),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="micro_controller",
            field=models.FileField(default=None, upload_to="files/"),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="sensor",
            field=models.FileField(default=None, upload_to="files/"),
        ),
    ]
