# Generated by Django 5.1.6 on 2025-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0003_alter_uploadedfile_actuator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="actuator",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="micro_controller",
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="sensor",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
    ]
