# Generated by Django 5.1.6 on 2025-02-17 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0004_remove_uploadedfile_actuator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="sensor",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="files/"
            ),
            preserve_default=False,
        ),
    ]
