# Generated by Django 5.1.6 on 2025-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file1", models.FileField(upload_to="uploads/file1/")),
                ("file2", models.FileField(upload_to="uploads/file2/")),
                ("file3", models.FileField(upload_to="uploads/file3/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
